name: Agent test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies & build
        run: |
          yarn
          yarn build
      - name: Run in node
        run: |
          cd testing/spawn-testing
          yarn test
      - name: Run in chrome
        run: |
          cd testing/spawn-testing
          yarn test --browser
