name: Agent test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies & build
        run: |
          yarn
          yarn build
      - name: Sync test in node
        run: |
          cd testing/spawn-testing
          DEBUG=dxos:spawn-testing:* node -r @babel/register src/tests/sync.js
      - name: Sync test in chrome
        run: |
          cd testing/spawn-testing
          DEBUG=dxos:spawn-testing:* node -r @babel/register src/tests/sync.js --browser

