#
# Copyright 2020 DXOS.org
#

name: Publish beta branch to NPM (beta branch => x.x.x-beta.0)

on:
  push:
    branches:
      - beta

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Build and NPM publish
          # config the git user
        - run: git config --global user.email "devops@dxos.org"
        - run: git config --global user.name "DXOS.org"

          # lint
        - run: yarn
        - run: yarn lint:lockfile
        - run: yarn lint

          # build and test
        - run: yarn build
        - run: yarn test

          # clean the environment
        - run: git reset --hard

          # set the version
        - run: VERSION=`cat package.json | grep '"version":' | awk '{ print $2 }' | sed 's/[",]//g'`
        - run: yarn lerna version ${VERSION}-beta.0 --no-git-tag-version -y
        - run: git commit -am "v$VERSION-beta.0"
        - run: git push

          # set the tag
        - run: git tag -f "v$VERSION-beta.0"
        - run: git push --tags -f

          # publish to NPM
        - run: yarn lerna publish from-package --force-publish -y --dist-tag="beta"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
