#
# Copyright 2020 DXOS.org
#

name: Publish to NPM (main branch => x.x.x-alpha.0)

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: dxos/release-please-action@v0.0.100
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: '@dxos/sdk'
      - uses: actions/checkout@v2
        # Only publish when a new release is created.
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - name: Lerna Publish
        run: |
          git config --global user.email "devops@dxos.org"
          git config --global user.name "DXOS.org"
          yarn
          yarn lint:lockfile
          yarn build
          yarn lint
          yarn test
          git reset --hard
          yarn lerna version --exact `echo "${{ steps.release.outputs.tag_name }}" | sed 's/^v//'`-alpha.0 --no-git-tag-version -y
          git commit -am "${{ steps.release.outputs.tag_name }}"-alpha.0
          git push
          git tag -f "${{ steps.release.outputs.tag_name }}"-alpha.0
          git push --tags -f
          git push --delete origin "${{ steps.release.outputs.tag_name }}"
          yarn lerna publish from-package --force-publish -y --dist-tag="alpha"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
