#
# Copyright 2020 DXOS.org
#

name: Run all tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # checkout and install
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile

      # lint
      - run: yarn lint:lockfile
      - run: yarn lint:versions
      - run: yarn lint

      # build
      - run: yarn build

      # jest tests with coverage
      - run: yarn test:coverage
      - uses: dxos/jest-reporter-action@0.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: "yarn --silent c8 report"

      # The c8 tool leaves tmp folder which is large, we don't want it uploaded to artifacts
      - run: rm -rf coverage/tmp
      # upload coverage report
      # zip file: https://github.com/actions/upload-artifact#zipped-artifact-downloads
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage

      # test playwright
      - run: yarn build:storybook
      - run: yarn test:playwright
